# Generated by Django 4.0.3 on 2023-02-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pogooda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='photo',
            field=models.ImageField(blank='True', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
